version: '3'

services:
  aws-cli:
    image: mikesir87/aws-cli:2.1.6
    container_name: web-aws-cli
    network_mode: host
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env
  
  node:
    image: node:14
    container_name: web-node-14
    network_mode: host
    volumes:
      - ./frontend:/app
    working_dir: /app
