AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:  
  Function:
    Runtime: nodejs12.x
    CodeUri: lambda
    Timeout: 15

Resources:
  CoursesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: courses
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  AuthorsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: authors
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  GetAllAuthorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-all-authors
      Handler: get-all-authors.handler
      Environment:
        Variables:
          AUTHORS_TABLE: !Ref AuthorsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthorsTable
      
  SaveOneCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: save-one-course
      Handler: save-one-course.handler
      Environment:
        Variables:
          COURSES_TABLE: !Ref CoursesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable
      
  UpdateOneCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-one-course
      Handler: update-one-course.handler
      Environment:
        Variables:
          COURSES_TABLE: !Ref CoursesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable

  GetAllCoursesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-all-courses
      Handler: get-all-courses.handler
      Environment:
        Variables:
          COURSES_TABLE: !Ref CoursesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable

  GetOneCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-one-course
      Handler: get-one-course.handler
      Environment:
        Variables:
          COURSES_TABLE: !Ref CoursesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable

  DeleteOneCourseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: delete-one-course
      Handler: delete-one-course.handler
      Environment:
        Variables:
          COURSES_TABLE: !Ref CoursesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CoursesTable
